spring.application.name=auth

spring.datasource.url=jdbc:postgresql://localhost:5432/observatorio
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=observatorio-ucundinamarca-secret-key-jwt-2026-0123456789abcdef
jwt.expiration-ms=86400000

server.port=8080